<?
$config=array();
$config["db"]=array();
$config["db"]["host"]="";
$config["db"]["user"]="";
$config["db"]["pass"]="";
$config["db"]["db"]="";
$config["demomode"]=false;
$config["twitter"]["consumer_key"]="";
$config["twitter"]["consumer_secret"]="";
$config["facebook"]["app_id"]="";
$config["facebook"]["app_secret"]="";
